### ISSUE TITLE
Wrong end of line configuration or files

### ISSUE THREAD

**Issue by matiasbeckerle** [arzafran/underpants#11]
Right now end of line is configured to use `crlf` which is kind of a lie because majority of files (or maybe all) are using `lf`. So... two alternatives:

1. Set `lf` in `.editorconfig`.
2. Apply `crlf` on all files.

I personally prefer option 1.

**Comment by arzafran** [comment]
I thought I had solved this but sure, go with n°1 always number one, like justin.

**Comment by matiasbeckerle** [comment]
Like Taylor!
