### ISSUE TITLE
Watching problem

### ISSUE THREAD

**Issue by FacuRiccardi** [arzafran/underpants#9]
I run Underpants with npm start. This does its job, but after this, its doesn´t keep watching and the processors of html, scss and js never run. I need to restart so that the processors function.

I don't know if I'm doing something wrong or if that is the function that it is supossed to do.

This is the text output I get:

$ npm start

> underpants@0.1.0 start C:\Users\Facundo\Desktop\Project\underpants
> npm run watch

> underpants@0.1.0 watch C:\Users\Facundo\Desktop\Project\underpants
> run-s build serve watch:*

> underpants@0.1.0 build C:\Users\Facundo\Desktop\Project\underpants
> run-p build:*

> underpants@0.1.0 build:scaffold C:\Users\Facundo\Desktop\Project\underpants
> mkdirp dist/css dist/js dist/images dist/svg

> underpants@0.1.0 build:html C:\Users\Facundo\Desktop\Project\underpants
> htmlprocessor index.html -o dist/index.html -r

> underpants@0.1.0 build:css C:\Users\Facundo\Desktop\Project\underpants
> run-s scss autoprefix

File "dist/index.html" created.

> underpants@0.1.0 build:js C:\Users\Facundo\Desktop\Project\underpants
> run-s lint uglify

> underpants@0.1.0 build:images C:\Users\Facundo\Desktop\Project\underpants
> run-p imagemin svgo

> underpants@0.1.0 scss C:\Users\Facundo\Desktop\Project\underpants
> node-sass-chokidar --recursive src/scss --output dist/css --output-style compressed

> underpants@0.1.0 lint C:\Users\Facundo\Desktop\Project\underpants
> eslint src/js/**

> underpants@0.1.0 imagemin C:\Users\Facundo\Desktop\Project\underpants
> imagemin src/images/** --out-dir=dist/images

> underpants@0.1.0 svgo C:\Users\Facundo\Desktop\Project\underpants
> svgo -f src/svg -o dist/svg

Rendering Complete, saving .css file...
Wrote CSS to C:\Users\Facundo\Desktop\Project\underpants\dist\css\base.css
Wrote 1 CSS files to C:\Users\Facundo\Desktop\Project\underpants\dist\css

C:\Users\Facundo\Desktop\Project\underpants\src\js\main.js
  1:13  warning  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style

✖ 1 problem (0 errors, 1 warning)

0 images minified
Processing directory 'src/svg':

{ Error: ENOENT: no such file or directory, scandir 'C:\Users\Facundo\Desktop\Project\underpants\src\svg'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\Facundo\\Desktop\\Project\\underpants\\src\\svg' }

> underpants@0.1.0 autoprefix C:\Users\Facundo\Desktop\Project\underpants
> postcss -u autoprefixer --autoprefixer.browsers ">; 5%, ie 11" -r dist/css/*

> underpants@0.1.0 uglify C:\Users\Facundo\Desktop\Project\underpants
> uglifyjs src/js/*.js -m -o dist/js/app.js && uglifyjs src/js/*.js -m -c -o dist/js/app.min.js

√ Finished dist\css\base.css (98ms)

> underpants@0.1.0 serve C:\Users\Facundo\Desktop\Project\underpants
> browser-sync start --startPath "dist/" --server --files "dist/css/*.css, dist/js/*.js, dist/*.html"

[BS] Access URLs:
 ------------------------------------------
       Local: http://localhost:3000/dist/
    External: http://192.168.0.7:3000/dist/
 ------------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.7:3001
 ------------------------------------------
[BS] Serving files from: ./
[BS] Watching files...

**Comment by arzafran** [comment]
So you're saying that once this is fired up, you save the .scss file and nothing happens? the output looks ok, just a single warning from eslint, but at the end it says it's watching.

try changing the backgorund color of the body and see if something happens on the browser. also we made some updates to the scripts so, if you can download the seed again and put your code in the src folder and start all over that will be better. 

Thanks for the info!

**Comment by matiasbeckerle** [comment]
@FacuRiccardi is right. It does't work for me either. None of the watchers seems to be working. Time to call...

![](https://upload.wikimedia.org/wikipedia/en/b/bc/Watchmen_film_poster.jpg)

**Comment by matiasbeckerle** [comment]
Hint:

- `npm run watch` doesn't work.
- `npm run watch:css` works.

**Comment by arzafran** [comment]
Hahhahaha well I'm on the road atm, so willing to take PRs :)

**Comment by matiasbeckerle** [comment]
`run-s` doesn't seem to work as you expect @arzafran. Probably you will need to use the old school run or found the root issue.

**Comment by matiasbeckerle** [comment]
Tried some shits without positive results. I'm mind exhausted right now. Going to take a look some other time.

**Comment by arzafran** [comment]
Thanks for everything, as soon as I get somewhere with a steady connection will try some stuff.

🐙

**Comment by matiasbeckerle** [comment]
Enjoy the ride duuude -- leave the issue for later. I might try some stuff also.

**Comment by matiasbeckerle** [comment]
After reading a little I would recommend to remove `nodemon` and go back to `onchange` approach. I couldn't find anything that plays well with all the current tools/options, at least for now, unless I miss something.

**Comment by arzafran** [comment]
This is fixed on commit 7651a78, please confirm so I can close this issue, and thanks for all the log, support, and feedback.

**Comment by matiasbeckerle** [comment]
Works for me! Nice job there!
